apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: 'registry.cn-hangzhou.aliyuncs.com/kubernetes-study/go-cicd:'
- name: /go-cicd
  newTag: 4e3c18c73f15a59d7ad924682949ca3143025ab7
