apiVersion: v1
kind: Service
metadata:
  name: go-cicd
  namespace: go-cicd
  labels:
    app: go-cicd
    version: v1
spec:
  ports:
    - name: http-5000
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: go-cicd
    version: v1
  type: NodePort
